name 'cesnet-java_ng'
version '2.1.2'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-java_ng'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'More parametrized Java installation'
description 'More parametrized Java installation'
project_page 'https://github.com/MetaCenterCloudPuppet/cesnet-java_ng'

dependency 'puppetlabs/apt', '>= 2.2.1 <3.0.0'
dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
